name: Sync Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to fork
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "bot@hikingclub-cn.com"
          git push "https://${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}@github.com/lizheyong/hiking-club-website.git" HEAD:main --force
