name: Sync to Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Sync to personal fork
        run: |
          git config --global user.name "hiking-club-bot"
          git config --global user.email "bot@hiking-club.com"
          git push "https://${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}@github.com/lizheyong/hiking-club-website.git" main:main --force
