name: Sync to Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4

      - name: Push to fork
        env:
          GH_TOKEN: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
        run: |
          git config --global user.name "lizheyong"
          git config --global user.email "740967133@mail.nwpu.edu.cn"
          
          echo "Verifying token is injected..."
          echo "GH_TOKEN starts with: ${GH_TOKEN:0:4}"  # 可选，验证是否非空

          git remote add fork https://x-access-token:${GH_TOKEN}@github.com/lizheyong/hiking-club-website.git
          git push -f fork main
