name: Sync to Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
        run: |
          # 直接使用 GitHub API 创建或更新引用
          LATEST_SHA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/hiking-club/hiking-club-website/git/refs/heads/main \
            | jq -r '.object.sha')
          
          echo "Latest SHA: $LATEST_SHA"
          
          # 更新 fork 的 main 分支引用
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/lizheyong/hiking-club-website/git/refs/heads/main \
            -d "{\"sha\":\"$LATEST_SHA\",\"force\":true}"
