name: Sync Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: hiking-club/hiking-club-website
          ref: main
          fetch-depth: 0
          
      - name: Push to fork
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
          repository: lizheyong/hiking-club-website
          branch: main
          force: true
