name: Debug Secret
on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret length
        env:
          TOKEN: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
        run: |
          echo "Token length: ${#TOKEN}"
          if [ -z "$TOKEN" ]; then
            echo "❌ Token is empty!"
          else
            echo "✅ Token exists"
            echo "Token starts with: ${TOKEN:0:4}..."
          fi
