name: Sync to Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push to fork
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync-bot@hiking-club.com"
          git push https://$GITHUB_TOKEN@github.com/lizheyong/hiking-club-website.git HEAD:main --force
