name: Sync Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitHub CLI
        run: |
          echo "${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}" | gh auth login --with-token
          
      - name: Push to fork using GitHub CLI
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "bot@hikingclub-cn.com"
          gh repo clone lizheyong/hiking-club-website temp-fork
          cd temp-fork
          git remote add upstream ../
          git fetch upstream
          git reset --hard upstream/main
          git push origin main --force
