name: Sync to Fork
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "hiking-club/hiking-club-website"
          source_branch: "main"
          destination_repo: "lizheyong/hiking-club-website"
          destination_branch: "main"
          github_token: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
