name: Sync to Fork
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/sync_fork.yml

jobs:
  sync:
    if: github.repository == 'hikingclub-cn/hiking-club-website'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout upstream
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录
          
      - name: Push to fork
        env:
          GH_TOKEN: ${{ secrets.PUSH_TO_FORK_TOKEN_WEBSITE }}
        run: |
          git config --global user.name "lizheyong"
          git config --global user.email "740967133@mail.nwpu.edu.cn"
          
          # ✅关键修复，移除默认身份 header，确保使用 token 认证
          git config --global --unset-all http.https://github.com/.extraheader || true
          
          # 添加 fork 远程仓库
          git remote add fork https://x-access-token:${GH_TOKEN}@github.com/lizheyong/hiking-club-website.git
          
          # 推送到 fork
          git push -f fork main
